lane :test do
  rustore_credentials(
    key_id: ENV["RUSTORE_KEY_ID"],
    private_key: ENV["RUSTORE_PRIVATE_KEY"],
#     private_key_file: ENV["RUSTORE_PRIVATE_KEY_FILE"],
  )
  upload_to_rustore(
    package_name: ENV["RUSTORE_PACKAGE_ID"],
    remove_active_draft: true
  )
end
